variables:
  CR_HOST_FULL: "repo url"
  CR_HOST_SHORT: "repo ip if use http"
  HOST_FULL: http://your_service_ip:6001/v1/full_analysis
  HOST_SHORT: http://your_service_ip:6001/v1/analysis
  GET_RESULT: http://your_service_ip:6001/v1/analysis
  SERVER_HOST: 185.250.207.230
  PROJECT_PATH: test1/open-ai-api

stages:
  - test
  - commit

test:
  image: alpine:latest
  stage: test
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /^CI.*/'
      when: never
    - when: always
  before_script:
    - apk add --no-cache curl jq
  script:
    - |
      UUID=$(curl -s -X POST "$HOST_FULL" \
        -H "Content-Type: application/json" \
        -d "{\"repo_url\": \"$CR_HOST_FULL\", \"gitlab_token\": \"$TOKEN\", \"commit_hash\": \"$CI_COMMIT_SHA\"}" \
        | jq -r .uuid)
      echo "Received UUID: $UUID"

    - |
      STATUS="Not"
      while [ "$STATUS" != "success" ]; do
        RESPONSE=$(curl -s -X GET "$GET_RESULT" \
          -H "Content-Type: application/json" \
          -d "{\"uuid\": \"$UUID\"}")
        echo "Response: $RESPONSE"
        STATUS=$(echo "$RESPONSE" | jq -r .status)
        sleep 10
      done

    - |
      curl -s -X GET "$GET_RESULT" \
        -H "Content-Type: application/json" \
        -d "{\"uuid\": \"$UUID\"}" | jq -r .content > report.md

  artifacts:
    paths:
      - report.md
    expire_in: 1 week

commit_report:
  stage: commit
  image: alpine:latest
  needs: [test]
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /^CI.*/'
      when: never
    - when: always
  before_script:
    - apk add --no-cache git
  script:
    - git config --global user.email "test2@gmail.com"
    - git config --global user.name "CI Bot"
    - git clone "http://oauth2:${TOKEN}@$CR_HOST_SHORT"
    - cd open-ai-api
    - cp ../report.md .
    - mv report.md README.md
    - git add README.md
    - |
      if ! git diff --cached --quiet; then
        git commit -m "CI: добавлен отчёт анализа для $CI_COMMIT_SHORT_SHA"
        git push origin HEAD:$CI_COMMIT_REF_NAME
      else
        echo "Нет изменений для коммита"
      fi
#